# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/comment
Accept: application/json

###
GET http://localhost:8080/user
Accept: application/json

###
GET http://localhost:8080/user/gs@dgsw
Accept: application/json

###
POST http://localhost:8080/user
Content-Type: application/json

{
  "userName": "hyoseong",
  "email": "gs@dgsw"
}

###
PUT http://localhost:8080/user
Content-Type: application/json

{
  "userName": "seonghyo",
  "email": "gs@dgsw"
}

###
DELETE http://localhost:8080/user/100
Accept: application/json

###
POST http://localhost:8080/comment
Content-Type: application/json

{
  "userId" : 100,
  "content" : "HELLO!"
}

###
PUT http://localhost:8080/comment
Content-Type: application/json

{
  "id" : 67,
  "content" : "GOOD BYE!"
}

###
DELETE http://localhost:8080/comment/33
Accept: application/json

###